### ISSUE TITLE
Put TPL path into config variable

### ISSUE THREAD

**Issue by cadorn** [hookflash/obsolete.op-identity-provider-server-php#74] opened 2014-05-30 18:11 UTC
This path:

https://github.com/openpeer/op-identity-provider-server-php/blob/1cd78ff84bfe4e4eff87b211323d58dce4d894e4/idprovider.com/public/login.php#L89

should be in a config variable so we can set the proper location on hcs-stack-integration.

$feature https://github.com/hookflashco/hcs-stack/issues/49

**Comment by RickHeuft** [comment] 2014-05-30 18:24
Hi Christoph.

Thanks for the heads up.  I'm assuming this means:

git config --add TPL https://github.com/openpeer/op-identity-provider-server-php/blob/1cd78ff84bfe4e4eff87b211323d58dce4d894e4/idprovider.com/public/login.php#L89

Do I just have to do this just once?

Do I have to clone the repo again?

**Comment by cadorn** [comment] 2014-05-30 18:49
@RickHeuft I think you are getting a few concepts confused.

The issue is about a config option that needs to be added in the code.

You seem to be asking about how to pull changes to code using git?

**Comment by RickHeuft** [comment] 2014-05-30 18:53
Sorry.  I got the email just moments after doing my first clone so I thought is was intended for me.

**Comment by elagerway** [comment] 2014-05-30 18:53
Rick, please do not close issues not assigned to you.

**Comment by adriano-maljkovic** [comment] 2014-06-01 08:52
done: 

http://hcs-stack-integration-php-ib07591e-0.vm.opp.me/op-identity-provider-server-php/login.php

**Closed as completed by adriano-maljkovic** 2014-06-01 08:52 UTC
Labels: IMPORTANT, BLOCKING
